"""
Taxonomy presets for different use cases.
Each preset defines a first-level base taxonomy optimized for specific domains.
"""

from enum import Enum
from typing import ClassVar


class TaxonomyVersion(Enum):
    """Available taxonomy versions for different use cases."""

    GENERAL = "general"
    AGENT_CONVERSATION = "agent_conversation"
    WORKFLOW_AUTOMATION = "workflow_automation"
    CUSTOMER_SERVICE = "customer_service"
    KNOWLEDGE_BASE = "knowledge_base"
    PERSONAL_ASSISTANT = "personal_assistant"


class TaxonomyPresets:
    """Defines base taxonomy presets for different use cases."""

    PRESETS: ClassVar[dict[TaxonomyVersion, dict[str, list[str]]]] = {
        TaxonomyVersion.GENERAL: {
            "profile": [
                "personal.identity",
                "personal.demographics",
                "personal.background",
                "personal.characteristics",
                "personal.values",
                "personal.beliefs",
                "professional.occupation",
                "professional.skills",
                "professional.experience",
                "professional.education",
                "professional.certifications",
                "professional.goals",
                "health.physical",
                "health.mental",
                "health.medical_history",
                "health.wellness_practices",
                "finance.income",
                "finance.expenses",
                "finance.investments",
                "finance.goals",
                "living.location",
                "living.housing",
                "living.arrangements",
                "living.neighborhood",
            ],
            "preferences": [
                "personal.lifestyle",
                "personal.hobbies",
                "personal.interests",
                "personal.entertainment",
                "personal.music",
                "personal.books",
                "personal.movies",
                "personal.food",
                "personal.travel",
                "personal.sports",
                "personal.art",
                "personal.fashion",
                "communication.style",
                "communication.channels",
                "communication.frequency",
                "communication.language",
                "work.environment",
                "work.schedule",
                "work.tools",
                "work.methods",
                "learning.style",
                "learning.topics",
                "learning.methods",
                "social.activities",
                "social.groups",
                "social.events",
            ],
            "experience": [
                "memories.childhood",
                "memories.adolescence",
                "memories.early_adulthood",
                "memories.recent",
                "memories.significant.events",
                "memories.significant.achievements",
                "memories.significant.challenges",
                "memories.significant.relationships",
                "memories.emotional.happy",
                "memories.emotional.sad",
                "memories.emotional.angry",
                "memories.emotional.fearful",
                "memories.emotional.proud",
                "memories.emotional.regretful",
                "travel.domestic",
                "travel.international",
                "travel.business",
                "travel.leisure",
                "education.primary",
                "education.secondary",
                "education.university",
                "education.graduate",
                "education.professional",
                "education.continuing",
                "work.jobs",
                "work.projects",
                "work.achievements",
                "work.challenges",
                "life_events.marriage",
                "life_events.divorce",
                "life_events.children",
                "life_events.death",
                "life_events.moving",
                "life_events.career_change",
            ],
            "context": [
                "current.location",
                "current.activity",
                "current.mood",
                "current.energy",
                "current.focus",
                "current.priorities",
                "current.challenges",
                "current.opportunities",
                "session.topic.main",
                "session.topic.secondary",
                "session.purpose",
                "session.progress",
                "session.decisions",
                "session.action_items",
                "temporal.today",
                "temporal.this_week",
                "temporal.this_month",
                "temporal.this_year",
                "temporal.past",
                "temporal.future",
                "environment.physical",
                "environment.social",
                "environment.digital",
                "environment.work",
                "environment.home",
            ],
            "knowledge": [
                "facts.personal",
                "facts.family",
                "facts.professional",
                "facts.academic",
                "facts.general",
                "skills.technical",
                "skills.interpersonal",
                "skills.creative",
                "skills.analytical",
                "skills.leadership",
                "skills.physical",
                "expertise.domain_specific",
                "expertise.cross_functional",
                "expertise.teaching",
                "expertise.consulting",
                "learning.current",
                "learning.planned",
                "learning.interests",
                "learning.resources",
                "information.sources",
                "information.trusted",
                "information.questionable",
                "procedures.work",
                "procedures.personal",
                "procedures.emergency",
            ],
            "relationships": [
                "people.family.immediate",
                "people.family.extended",
                "people.family.in_laws",
                "people.friends.close",
                "people.friends.casual",
                "people.friends.childhood",
                "people.friends.work",
                "people.colleagues.current",
                "people.colleagues.former",
                "people.colleagues.peers",
                "people.colleagues.supervisors",
                "people.colleagues.subordinates",
                "people.professional.clients",
                "people.professional.vendors",
                "people.professional.partners",
                "people.professional.mentors",
                "people.professional.mentees",
                "people.community.neighbors",
                "people.community.groups",
                "people.community.organizations",
                "people.romantic.current",
                "people.romantic.former",
                "people.acquaintances",
                "dynamics.supportive",
                "dynamics.challenging",
                "dynamics.neutral",
                "interactions.frequency",
                "interactions.quality",
                "interactions.history",
            ],
            "goals": [
                "categories.personal.health",
                "categories.personal.fitness",
                "categories.personal.relationships",
                "categories.personal.hobbies",
                "categories.personal.experiences",
                "categories.personal.growth",
                "categories.career.advancement",
                "categories.career.skills",
                "categories.career.change",
                "categories.career.entrepreneurship",
                "categories.financial.income",
                "categories.financial.savings",
                "categories.financial.investments",
                "categories.financial.debt",
                "categories.financial.retirement",
                "categories.education.formal",
                "categories.education.skills",
                "categories.education.certifications",
                "categories.education.languages",
                "timeline.immediate",
                "timeline.short_term",
                "timeline.medium_term",
                "timeline.long_term",
                "timeline.lifelong",
                "status.planning",
                "status.active",
                "status.paused",
                "status.completed",
                "status.abandoned",
            ],
            "behavior": [
                "patterns.daily",
                "patterns.weekly",
                "patterns.monthly",
                "patterns.seasonal",
                "patterns.work",
                "patterns.social",
                "patterns.health",
                "patterns.learning",
                "habits.positive",
                "habits.negative",
                "habits.developing",
                "habits.breaking",
                "reactions.stress",
                "reactions.conflict",
                "reactions.success",
                "reactions.failure",
                "reactions.change",
                "reactions.pressure",
                "decision_making.style",
                "decision_making.factors",
                "decision_making.speed",
                "decision_making.confidence",
                "communication.verbal",
                "communication.written",
                "communication.nonverbal",
                "communication.listening",
                "problem_solving.approach",
                "problem_solving.resources",
                "problem_solving.collaboration",
            ],
        },
        TaxonomyVersion.AGENT_CONVERSATION: {
            "conversation": [],
            "user_profile": [],
            "agent_state": [],
            "dialogue_history": [],
            "intent": [],
            "entities": [],
            "sentiment": [],
            "topics": [],
            "actions": [],
            "feedback": [],
        },
        TaxonomyVersion.WORKFLOW_AUTOMATION: {
            "workflows": [],
            "tasks": [],
            "triggers": [],
            "conditions": [],
            "actions": [],
            "integrations": [],
            "data_mappings": [],
            "schedules": [],
            "notifications": [],
            "errors": [],
            "logs": [],
            "metrics": [],
        },
        TaxonomyVersion.CUSTOMER_SERVICE: {
            "customers": [],
            "tickets": [],
            "issues": [],
            "products": [],
            "solutions": [],
            "escalations": [],
            "satisfaction": [],
            "faq": [],
            "policies": [],
            "communications": [],
            "analytics": [],
        },
        TaxonomyVersion.KNOWLEDGE_BASE: {
            "documents": [],
            "categories": [],
            "tags": [],
            "concepts": [],
            "definitions": [],
            "procedures": [],
            "references": [],
            "examples": [],
            "metadata": [],
            "versions": [],
            "permissions": [],
        },
        TaxonomyVersion.PERSONAL_ASSISTANT: {
            "personal_info": [
                "identity.name",
                "identity.age",
                "identity.location",
                "identity.occupation",
                "contact.phone",
                "contact.email",
                "contact.address",
                "emergency_contacts",
                "documents.identification",
                "documents.insurance",
                "documents.legal",
            ],
            "calendar": [
                "events.meetings",
                "events.appointments",
                "events.social",
                "events.travel",
                "events.recurring",
                "schedule.daily",
                "schedule.weekly",
                "schedule.monthly",
                "availability.work_hours",
                "availability.free_time",
                "conflicts.detected",
                "conflicts.resolved",
            ],
            "reminders": [
                "tasks.urgent",
                "tasks.important",
                "tasks.routine",
                "tasks.delegated",
                "deadlines.work",
                "deadlines.personal",
                "follow_ups.people",
                "follow_ups.projects",
                "recurring.daily",
                "recurring.weekly",
                "recurring.monthly",
                "recurring.yearly",
            ],
            "notes": [
                "meeting_notes",
                "ideas.creative",
                "ideas.business",
                "ideas.personal",
                "research.topics",
                "research.findings",
                "quotes.inspirational",
                "quotes.useful",
                "lists.shopping",
                "lists.todo",
                "lists.reference",
                "observations.people",
                "observations.trends",
            ],
            "contacts": [
                "people.family",
                "people.friends",
                "people.work.colleagues",
                "people.work.clients",
                "people.work.vendors",
                "people.professional.services",
                "people.medical.doctors",
                "people.medical.specialists",
                "organizations.work",
                "organizations.social",
                "organizations.professional",
                "organizations.service_providers",
            ],
            "preferences": [
                "communication.methods",
                "communication.timing",
                "notification.urgency_levels",
                "notification.channels",
                "scheduling.buffer_time",
                "scheduling.preferred_times",
                "travel.transportation",
                "travel.accommodation",
                "dining.cuisine",
                "dining.restrictions",
                "entertainment.types",
                "entertainment.venues",
                "shopping.brands",
                "shopping.stores",
            ],
            "routines": [
                "daily.morning",
                "daily.work_start",
                "daily.lunch",
                "daily.work_end",
                "daily.evening",
                "weekly.planning",
                "weekly.review",
                "weekly.social",
                "monthly.bills",
                "monthly.review",
                "seasonal.activities",
                "travel.preparation",
                "travel.follow_up",
            ],
            "health": [
                "medical.conditions",
                "medical.medications",
                "medical.allergies",
                "medical.appointments",
                "fitness.activities",
                "fitness.goals",
                "fitness.tracking",
                "mental_health.practices",
                "mental_health.support",
                "nutrition.diet",
                "nutrition.restrictions",
                "sleep.schedule",
                "sleep.quality",
            ],
            "finance": [
                "accounts.banking",
                "accounts.credit",
                "accounts.investment",
                "accounts.retirement",
                "budget.income",
                "budget.expenses",
                "budget.categories",
                "bills.recurring",
                "bills.due_dates",
                "investments.portfolio",
                "investments.goals",
                "taxes.documents",
                "taxes.deadlines",
            ],
            "projects": [
                "work.current",
                "work.completed",
                "work.planned",
                "personal.current",
                "personal.completed",
                "personal.planned",
                "home.maintenance",
                "home.improvement",
                "learning.courses",
                "learning.skills",
                "creative.writing",
                "creative.art",
                "creative.music",
            ],
            "learning": [
                "courses.online",
                "courses.formal",
                "books.reading",
                "books.to_read",
                "skills.technical",
                "skills.soft",
                "languages.studying",
                "languages.target",
                "certifications.pursuing",
                "certifications.maintaining",
                "conferences.attended",
                "conferences.planned",
            ],
        },
    }

    @classmethod
    def get_preset(cls, version: TaxonomyVersion) -> dict[str, list[str]]:
        """
        Get a taxonomy preset for a specific version.

        Args:
            version: The taxonomy version to retrieve

        Returns:
            Dictionary with first-level categories and their subcategories (empty for dynamic expansion)
        """
        return cls.PRESETS.get(version, cls.PRESETS[TaxonomyVersion.GENERAL]).copy()

    @classmethod
    def get_first_level_categories(cls, version: TaxonomyVersion) -> list[str]:
        """
        Get only the first-level categories for a taxonomy version.

        Args:
            version: The taxonomy version

        Returns:
            List of first-level category names
        """
        preset = cls.get_preset(version)
        return list(preset.keys())

    @classmethod
    def list_versions(cls) -> list[TaxonomyVersion]:
        """
        List all available taxonomy versions.

        Returns:
            List of available TaxonomyVersion enums
        """
        return list(TaxonomyVersion)
