"""
Taxonomy presets for different use cases.
Each preset defines a first-level base taxonomy optimized for specific domains.
"""

from enum import Enum
from typing import ClassVar


class TaxonomyVersion(Enum):
    """Available taxonomy versions for different use cases."""

    GENERAL = "general"
    AGENT_CONVERSATION = "agent_conversation"
    WORKFLOW_AUTOMATION = "workflow_automation"
    CUSTOMER_SERVICE = "customer_service"
    KNOWLEDGE_BASE = "knowledge_base"
    PERSONAL_ASSISTANT = "personal_assistant"


class TaxonomyPresets:
    """Defines base taxonomy presets for different use cases."""

    PRESETS: ClassVar[dict[TaxonomyVersion, dict[str, list[str]]]] = {
        TaxonomyVersion.GENERAL: {
            "profile": [
                # Personal Identity & Demographics
                "personal.identity.name.first",
                "personal.identity.name.middle",
                "personal.identity.name.last",
                "personal.identity.name.nicknames",
                "personal.identity.name.preferred",
                "personal.identity.gender.identity",
                "personal.identity.gender.pronouns",
                "personal.identity.sexual_orientation",
                "personal.identity.ethnicity",
                "personal.identity.nationality",
                "personal.identity.religion.current",
                "personal.identity.religion.background",
                "personal.demographics.age.current",
                "personal.demographics.age.birth_year",
                "personal.demographics.birth.date",
                "personal.demographics.birth.location",
                "personal.demographics.birth.hospital",
                "personal.demographics.marital_status",
                "personal.demographics.children.number",
                "personal.demographics.children.ages",
                "personal.demographics.children.names",
                "personal.demographics.languages.native",
                "personal.demographics.languages.fluent",
                "personal.demographics.languages.learning",
                # Personal Background & History
                "personal.background.family.parents.names",
                "personal.background.family.parents.occupations",
                "personal.background.family.siblings.number",
                "personal.background.family.siblings.names",
                "personal.background.family.siblings.relationships",
                "personal.background.family.extended.grandparents",
                "personal.background.family.extended.aunts_uncles",
                "personal.background.family.extended.cousins",
                "personal.background.childhood.location",
                "personal.background.childhood.schools",
                "personal.background.childhood.friends",
                "personal.background.childhood.activities",
                "personal.background.childhood.trauma",
                "personal.background.immigration.status",
                "personal.background.immigration.history",
                "personal.background.military.service",
                "personal.background.military.branch",
                "personal.background.military.rank",
                # Personal Characteristics & Traits
                "personal.characteristics.personality.type",
                "personal.characteristics.personality.mbti",
                "personal.characteristics.personality.enneagram",
                "personal.characteristics.personality.introvert_extrovert",
                "personal.characteristics.traits.strengths",
                "personal.characteristics.traits.weaknesses",
                "personal.characteristics.traits.quirks",
                "personal.characteristics.communication.style",
                "personal.characteristics.communication.preferred_medium",
                "personal.characteristics.learning.style",
                "personal.characteristics.learning.pace",
                "personal.characteristics.decision_making.style",
                "personal.characteristics.conflict.style",
                "personal.characteristics.humor.type",
                "personal.characteristics.humor.preferences",
                # Values, Beliefs & Philosophy
                "personal.values.core.list",
                "personal.values.core.priorities",
                "personal.values.family.importance",
                "personal.values.career.importance",
                "personal.values.money.importance",
                "personal.values.health.importance",
                "personal.values.relationships.importance",
                "personal.beliefs.political.party",
                "personal.beliefs.political.views",
                "personal.beliefs.political.involvement",
                "personal.beliefs.social.justice",
                "personal.beliefs.environmental.views",
                "personal.beliefs.spiritual.practices",
                "personal.beliefs.afterlife.views",
                "personal.philosophy.life.purpose",
                "personal.philosophy.success.definition",
                "personal.philosophy.happiness.definition",
                # Professional Profile
                "professional.current.company",
                "professional.current.title",
                "professional.current.department",
                "professional.current.manager",
                "professional.current.team_size",
                "professional.current.responsibilities",
                "professional.current.start_date",
                "professional.current.salary.base",
                "professional.current.salary.bonus",
                "professional.current.benefits",
                "professional.history.previous_companies",
                "professional.history.previous_titles",
                "professional.history.employment_gaps",
                "professional.history.terminations",
                "professional.history.achievements",
                "professional.skills.technical.programming",
                "professional.skills.technical.software",
                "professional.skills.technical.certifications",
                "professional.skills.soft.leadership",
                "professional.skills.soft.communication",
                "professional.skills.soft.teamwork",
                "professional.skills.industry.expertise",
                "professional.skills.industry.knowledge",
                "professional.network.mentors",
                "professional.network.colleagues",
                "professional.network.industry_contacts",
                # Education Background
                "professional.education.elementary.school",
                "professional.education.elementary.location",
                "professional.education.high_school.name",
                "professional.education.high_school.location",
                "professional.education.high_school.graduation_year",
                "professional.education.high_school.gpa",
                "professional.education.college.name",
                "professional.education.college.location",
                "professional.education.college.degree",
                "professional.education.college.major",
                "professional.education.college.minor",
                "professional.education.college.graduation_year",
                "professional.education.college.gpa",
                "professional.education.graduate.school",
                "professional.education.graduate.degree",
                "professional.education.graduate.field",
                "professional.education.graduate.thesis",
                "professional.education.continuing.courses",
                "professional.education.continuing.certifications",
                "professional.education.continuing.workshops",
                # Health Profile
                "health.physical.height",
                "health.physical.weight",
                "health.physical.blood_type",
                "health.physical.fitness_level",
                "health.physical.exercise.frequency",
                "health.physical.exercise.types",
                "health.physical.exercise.duration",
                "health.physical.diet.type",
                "health.physical.diet.restrictions",
                "health.physical.diet.allergies",
                "health.physical.sleep.hours",
                "health.physical.sleep.schedule",
                "health.physical.sleep.quality",
                "health.mental.conditions.diagnosed",
                "health.mental.conditions.suspected",
                "health.mental.therapy.current",
                "health.mental.therapy.history",
                "health.mental.medication.current",
                "health.mental.medication.history",
                "health.mental.stress.level",
                "health.mental.stress.triggers",
                "health.mental.coping.strategies",
                "health.medical.conditions.chronic",
                "health.medical.conditions.hereditary",
                "health.medical.surgeries.history",
                "health.medical.hospitalizations.history",
                "health.medical.doctors.primary",
                "health.medical.doctors.specialists",
                "health.medical.insurance.provider",
                "health.medical.insurance.coverage",
                # Financial Profile
                "finance.income.primary.amount",
                "finance.income.primary.frequency",
                "finance.income.secondary.sources",
                "finance.income.secondary.amounts",
                "finance.income.passive.sources",
                "finance.income.passive.amounts",
                "finance.expenses.housing.rent_mortgage",
                "finance.expenses.housing.utilities",
                "finance.expenses.housing.maintenance",
                "finance.expenses.transportation.car_payment",
                "finance.expenses.transportation.insurance",
                "finance.expenses.transportation.gas",
                "finance.expenses.food.groceries",
                "finance.expenses.food.dining_out",
                "finance.expenses.healthcare.insurance",
                "finance.expenses.healthcare.out_of_pocket",
                "finance.expenses.entertainment.budget",
                "finance.expenses.clothing.budget",
                "finance.debt.credit_cards.balance",
                "finance.debt.credit_cards.minimum_payment",
                "finance.debt.student_loans.balance",
                "finance.debt.student_loans.payment",
                "finance.debt.mortgage.balance",
                "finance.debt.mortgage.payment",
                "finance.debt.other.types",
                "finance.savings.emergency_fund.amount",
                "finance.savings.emergency_fund.goal",
                "finance.savings.retirement.amount",
                "finance.savings.retirement.contribution",
                "finance.investments.stocks.portfolio",
                "finance.investments.bonds.portfolio",
                "finance.investments.real_estate.properties",
                "finance.investments.crypto.portfolio",
                "finance.credit.score.current",
                "finance.credit.score.history",
                "finance.banking.primary.bank",
                "finance.banking.primary.accounts",
                # Living Situation
                "living.current.address.street",
                "living.current.address.city",
                "living.current.address.state",
                "living.current.address.zip",
                "living.current.address.country",
                "living.current.type.house_apartment",
                "living.current.ownership.rent_own",
                "living.current.size.bedrooms",
                "living.current.size.bathrooms",
                "living.current.size.square_feet",
                "living.current.roommates.number",
                "living.current.roommates.names",
                "living.current.roommates.relationships",
                "living.current.pets.types",
                "living.current.pets.names",
                "living.current.pets.ages",
                "living.history.previous_addresses",
                "living.history.moves.frequency",
                "living.history.moves.reasons",
                "living.neighborhood.safety.rating",
                "living.neighborhood.walkability.score",
                "living.neighborhood.amenities.nearby",
                "living.neighborhood.schools.quality",
                "living.neighborhood.demographics",
                "living.transportation.primary.method",
                "living.transportation.car.make_model",
                "living.transportation.car.year",
                "living.transportation.public.usage",
                # Relationships & Social
                "relationships.romantic.status.current",
                "relationships.romantic.partner.name",
                "relationships.romantic.partner.occupation",
                "relationships.romantic.history.significant",
                "relationships.romantic.preferences.type",
                "relationships.family.relationship.parents",
                "relationships.family.relationship.siblings",
                "relationships.family.relationship.children",
                "relationships.family.relationship.extended",
                "relationships.friendships.close.number",
                "relationships.friendships.close.names",
                "relationships.friendships.close.duration",
                "relationships.friendships.social_circle.size",
                "relationships.professional.mentors",
                "relationships.professional.colleagues",
                "relationships.professional.networking",
                "relationships.social.groups.memberships",
                "relationships.social.groups.activities",
                "relationships.social.media.platforms",
                "relationships.social.media.usage",
                # Goals & Aspirations
                "goals.personal.short_term.list",
                "goals.personal.short_term.timeline",
                "goals.personal.long_term.list",
                "goals.personal.long_term.timeline",
                "goals.career.next_role.target",
                "goals.career.next_role.timeline",
                "goals.career.industry.change",
                "goals.career.salary.target",
                "goals.career.skills.development",
                "goals.financial.net_worth.target",
                "goals.financial.retirement.age",
                "goals.financial.retirement.amount",
                "goals.health.fitness.targets",
                "goals.health.wellness.improvements",
                "goals.travel.destinations.bucket_list",
                "goals.travel.experiences.desired",
                "goals.learning.subjects.interests",
                "goals.learning.degrees.pursuing",
                "goals.relationships.family.plans",
                "goals.relationships.social.improvements",
                "goals.lifestyle.changes.desired",
                "goals.legacy.impact.desired",
            ],
            "preferences": [
                "personal.lifestyle",
                "personal.hobbies",
                "personal.interests",
                "personal.entertainment",
                "personal.music",
                "personal.books",
                "personal.movies",
                "personal.food",
                "personal.travel",
                "personal.sports",
                "personal.art",
                "personal.fashion",
                "communication.style",
                "communication.channels",
                "communication.frequency",
                "communication.language",
                "work.environment",
                "work.schedule",
                "work.tools",
                "work.methods",
                "learning.style",
                "learning.topics",
                "learning.methods",
                "social.activities",
                "social.groups",
                "social.events",
            ],
            "experience": [
                "memories.childhood",
                "memories.adolescence",
                "memories.early_adulthood",
                "memories.recent",
                "memories.significant.events",
                "memories.significant.achievements",
                "memories.significant.challenges",
                "memories.significant.relationships",
                "memories.emotional.happy",
                "memories.emotional.sad",
                "memories.emotional.angry",
                "memories.emotional.fearful",
                "memories.emotional.proud",
                "memories.emotional.regretful",
                "travel.domestic",
                "travel.international",
                "travel.business",
                "travel.leisure",
                "education.primary",
                "education.secondary",
                "education.university",
                "education.graduate",
                "education.professional",
                "education.continuing",
                "work.jobs",
                "work.projects",
                "work.achievements",
                "work.challenges",
                "life_events.marriage",
                "life_events.divorce",
                "life_events.children",
                "life_events.death",
                "life_events.moving",
                "life_events.career_change",
            ],
            "knowledge": [
                "facts.personal",
                "facts.family",
                "facts.professional",
                "facts.academic",
                "facts.general",
                "skills.technical",
                "skills.interpersonal",
                "skills.creative",
                "skills.analytical",
                "skills.leadership",
                "skills.physical",
                "expertise.domain_specific",
                "expertise.cross_functional",
                "expertise.teaching",
                "expertise.consulting",
                "learning.current",
                "learning.planned",
                "learning.interests",
                "learning.resources",
                "information.sources",
                "information.trusted",
                "information.questionable",
                "procedures.work",
                "procedures.personal",
                "procedures.emergency",
            ],
            "relationships": [
                "people.family.immediate",
                "people.family.extended",
                "people.family.in_laws",
                "people.friends.close",
                "people.friends.casual",
                "people.friends.childhood",
                "people.friends.work",
                "people.colleagues.current",
                "people.colleagues.former",
                "people.colleagues.peers",
                "people.colleagues.supervisors",
                "people.colleagues.subordinates",
                "people.professional.clients",
                "people.professional.vendors",
                "people.professional.partners",
                "people.professional.mentors",
                "people.professional.mentees",
                "people.community.neighbors",
                "people.community.groups",
                "people.community.organizations",
                "people.romantic.current",
                "people.romantic.former",
                "people.acquaintances",
                "dynamics.supportive",
                "dynamics.challenging",
                "dynamics.neutral",
                "interactions.frequency",
                "interactions.quality",
                "interactions.history",
            ],
            "goals": [
                "categories.personal.health",
                "categories.personal.fitness",
                "categories.personal.relationships",
                "categories.personal.hobbies",
                "categories.personal.experiences",
                "categories.personal.growth",
                "categories.career.advancement",
                "categories.career.skills",
                "categories.career.change",
                "categories.career.entrepreneurship",
                "categories.financial.income",
                "categories.financial.savings",
                "categories.financial.investments",
                "categories.financial.debt",
                "categories.financial.retirement",
                "categories.education.formal",
                "categories.education.skills",
                "categories.education.certifications",
                "categories.education.languages",
                "timeline.immediate",
                "timeline.short_term",
                "timeline.medium_term",
                "timeline.long_term",
                "timeline.lifelong",
                "status.planning",
                "status.active",
                "status.paused",
                "status.completed",
                "status.abandoned",
            ],
            "behavior": [
                "patterns.daily",
                "patterns.weekly",
                "patterns.monthly",
                "patterns.seasonal",
                "patterns.work",
                "patterns.social",
                "patterns.health",
                "patterns.learning",
                "habits.positive",
                "habits.negative",
                "habits.developing",
                "habits.breaking",
                "reactions.stress",
                "reactions.conflict",
                "reactions.success",
                "reactions.failure",
                "reactions.change",
                "reactions.pressure",
                "decision_making.style",
                "decision_making.factors",
                "decision_making.speed",
                "decision_making.confidence",
                "communication.verbal",
                "communication.written",
                "communication.nonverbal",
                "communication.listening",
                "problem_solving.approach",
                "problem_solving.resources",
                "problem_solving.collaboration",
            ],
            "entity": [
                "people.mentioned.family_members",
                "people.mentioned.friends",
                "people.mentioned.colleagues",
                "people.mentioned.acquaintances",
                "people.mentioned.public_figures",
                "people.mentioned.service_providers",
                "places.locations.cities",
                "places.locations.countries",
                "places.locations.neighborhoods",
                "places.locations.addresses",
                "places.buildings.homes",
                "places.buildings.offices",
                "places.buildings.restaurants",
                "places.buildings.shops",
                "places.buildings.hospitals",
                "places.buildings.schools",
                "places.venues.events",
                "places.venues.entertainment",
                "places.venues.recreation",
                "time.dates.specific",
                "time.dates.relative",
                "time.periods.durations",
                "time.periods.frequencies",
                "time.events.appointments",
                "time.events.deadlines",
                "time.events.milestones",
                "time.events.celebrations",
                "objects.items.personal",
                "objects.items.household",
                "objects.items.technology",
                "objects.items.vehicles",
                "objects.items.clothing",
                "objects.items.tools",
                "objects.documents.legal",
                "objects.documents.financial",
                "objects.documents.medical",
                "objects.documents.educational",
                "objects.media.books",
                "objects.media.movies",
                "objects.media.music",
                "objects.media.articles",
                "organizations.companies.current",
                "organizations.companies.previous",
                "organizations.institutions.educational",
                "organizations.institutions.medical",
                "organizations.institutions.government",
                "organizations.groups.social",
                "organizations.groups.professional",
                "organizations.groups.community",
                "events.activities.work_related",
                "events.activities.social",
                "events.activities.recreational",
                "events.activities.educational",
                "events.milestones.personal",
                "events.milestones.professional",
                "events.milestones.family",
                "events.transactions.purchases",
                "events.transactions.services",
                "events.transactions.financial",
                "concepts.topics.discussed",
                "concepts.topics.interests",
                "concepts.skills.mentioned",
                "concepts.skills.learning",
                "concepts.ideas.shared",
                "concepts.problems.identified",
                "concepts.solutions.proposed",
                "measurements.quantities.amounts",
                "measurements.quantities.distances",
                "measurements.quantities.durations",
                "measurements.financial.costs",
                "measurements.financial.income",
                "measurements.physical.dimensions",
                "measurements.physical.weights",
            ],
            "language": [
                "abbreviations.common",
                "abbreviations.technical",
                "abbreviations.organizational",
                "abbreviations.medical",
                "abbreviations.personal",
                "slang.expressions",
                "slang.generational",
                "slang.regional",
                "slang.professional",
                "terminology.technical",
                "terminology.medical",
                "terminology.legal",
                "terminology.financial",
                "terminology.academic",
                "terminology.industry_specific",
                "phrases.idioms",
                "phrases.colloquialisms",
                "phrases.catchphrases",
                "phrases.quotes",
                "phrases.sayings",
                "communication_style.formal",
                "communication_style.informal",
                "communication_style.professional",
                "communication_style.casual",
                "communication_style.emotional",
                "tone.sarcastic",
                "tone.humorous",
                "tone.serious",
                "tone.enthusiastic",
                "tone.concerned",
                "tone.frustrated",
                "expressions.emotions",
                "expressions.reactions",
                "expressions.opinions",
                "expressions.preferences",
                "languages.native",
                "languages.learned",
                "languages.studying",
                "languages.mentioned",
                "dialects.regional",
                "dialects.cultural",
                "dialects.professional",
                "code_switching.languages",
                "code_switching.registers",
                "vocabulary.new_words",
                "vocabulary.difficult_words",
                "vocabulary.specialized",
                "grammar.errors",
                "grammar.patterns",
                "grammar.corrections",
                "pronunciation.challenges",
                "pronunciation.accents",
                "pronunciation.variations",
                "wordplay.puns",
                "wordplay.jokes",
                "wordplay.rhymes",
                "wordplay.alliterations",
                "metaphors.used",
                "metaphors.explained",
                "analogies.made",
                "analogies.understood",
                "cultural_references.pop_culture",
                "cultural_references.historical",
                "cultural_references.literary",
                "cultural_references.religious",
            ],
            "topics": [
                "current_events.news",
                "current_events.politics",
                "current_events.social_issues",
                "current_events.local_events",
                "current_events.global_events",
                "technology.computers",
                "technology.smartphones",
                "technology.internet",
                "technology.artificial_intelligence",
                "technology.social_media",
                "technology.software",
                "technology.gadgets",
                "health.fitness",
                "health.nutrition",
                "health.mental_health",
                "health.medical_conditions",
                "health.wellness",
                "health.healthcare_system",
                "health.medications",
                "education.schools",
                "education.learning_methods",
                "education.courses",
                "education.skills_development",
                "education.certifications",
                "education.research",
                "career.job_search",
                "career.workplace_issues",
                "career.professional_development",
                "career.industry_trends",
                "career.entrepreneurship",
                "career.retirement",
                "relationships.family",
                "relationships.friendships",
                "relationships.romantic",
                "relationships.colleagues",
                "relationships.social_circles",
                "relationships.conflicts",
                "relationships.communication",
                "entertainment.movies",
                "entertainment.tv_shows",
                "entertainment.music",
                "entertainment.books",
                "entertainment.games",
                "entertainment.sports",
                "entertainment.celebrities",
                "lifestyle.fashion",
                "lifestyle.beauty",
                "lifestyle.home_decor",
                "lifestyle.cooking",
                "lifestyle.travel",
                "lifestyle.hobbies",
                "lifestyle.shopping",
                "finance.budgeting",
                "finance.investing",
                "finance.saving",
                "finance.debt",
                "finance.insurance",
                "finance.taxes",
                "finance.real_estate",
                "social_issues.equality",
                "social_issues.environment",
                "social_issues.human_rights",
                "social_issues.community",
                "social_issues.activism",
                "social_issues.diversity",
                "personal_growth.self_improvement",
                "personal_growth.mindfulness",
                "personal_growth.spirituality",
                "personal_growth.therapy",
                "personal_growth.life_philosophy",
                "personal_growth.goal_setting",
                "science.research",
                "science.discoveries",
                "science.theories",
                "science.experiments",
                "science.innovations",
                "arts.visual_arts",
                "arts.performing_arts",
                "arts.literature",
                "arts.music_theory",
                "arts.creative_process",
                "culture.traditions",
                "culture.customs",
                "culture.languages",
                "culture.history",
                "culture.anthropology",
                "weather.conditions",
                "weather.seasons",
                "weather.climate_change",
                "food.recipes",
                "food.restaurants",
                "food.dietary_preferences",
                "food.nutrition",
                "food.cooking_techniques",
                "transportation.vehicles",
                "transportation.public_transit",
                "transportation.travel_planning",
                "home.maintenance",
                "home.renovation",
                "home.organization",
                "home.gardening",
                "pets.care",
                "pets.behavior",
                "pets.health",
                "philosophy.ethics",
                "philosophy.existence",
                "philosophy.meaning",
                "philosophy.morality",
            ],
        },
        TaxonomyVersion.AGENT_CONVERSATION: {
            "conversation": [],
            "user_profile": [],
            "agent_state": [],
            "dialogue_history": [],
            "intent": [],
            "entities": [],
            "sentiment": [],
            "topics": [],
            "actions": [],
            "feedback": [],
        },
        TaxonomyVersion.WORKFLOW_AUTOMATION: {
            "workflows": [],
            "tasks": [],
            "triggers": [],
            "conditions": [],
            "actions": [],
            "integrations": [],
            "data_mappings": [],
            "schedules": [],
            "notifications": [],
            "errors": [],
            "logs": [],
            "metrics": [],
        },
        TaxonomyVersion.CUSTOMER_SERVICE: {
            "customers": [],
            "tickets": [],
            "issues": [],
            "products": [],
            "solutions": [],
            "escalations": [],
            "satisfaction": [],
            "faq": [],
            "policies": [],
            "communications": [],
            "analytics": [],
        },
        TaxonomyVersion.KNOWLEDGE_BASE: {
            "documents": [],
            "categories": [],
            "tags": [],
            "concepts": [],
            "definitions": [],
            "procedures": [],
            "references": [],
            "examples": [],
            "metadata": [],
            "versions": [],
            "permissions": [],
        },
        TaxonomyVersion.PERSONAL_ASSISTANT: {
            "personal_info": [
                "identity.name",
                "identity.age",
                "identity.location",
                "identity.occupation",
                "contact.phone",
                "contact.email",
                "contact.address",
                "emergency_contacts",
                "documents.identification",
                "documents.insurance",
                "documents.legal",
            ],
            "calendar": [
                "events.meetings",
                "events.appointments",
                "events.social",
                "events.travel",
                "events.recurring",
                "schedule.daily",
                "schedule.weekly",
                "schedule.monthly",
                "availability.work_hours",
                "availability.free_time",
                "conflicts.detected",
                "conflicts.resolved",
            ],
            "reminders": [
                "tasks.urgent",
                "tasks.important",
                "tasks.routine",
                "tasks.delegated",
                "deadlines.work",
                "deadlines.personal",
                "follow_ups.people",
                "follow_ups.projects",
                "recurring.daily",
                "recurring.weekly",
                "recurring.monthly",
                "recurring.yearly",
            ],
            "notes": [
                "meeting_notes",
                "ideas.creative",
                "ideas.business",
                "ideas.personal",
                "research.topics",
                "research.findings",
                "quotes.inspirational",
                "quotes.useful",
                "lists.shopping",
                "lists.todo",
                "lists.reference",
                "observations.people",
                "observations.trends",
            ],
            "contacts": [
                "people.family",
                "people.friends",
                "people.work.colleagues",
                "people.work.clients",
                "people.work.vendors",
                "people.professional.services",
                "people.medical.doctors",
                "people.medical.specialists",
                "organizations.work",
                "organizations.social",
                "organizations.professional",
                "organizations.service_providers",
            ],
            "preferences": [
                "communication.methods",
                "communication.timing",
                "notification.urgency_levels",
                "notification.channels",
                "scheduling.buffer_time",
                "scheduling.preferred_times",
                "travel.transportation",
                "travel.accommodation",
                "dining.cuisine",
                "dining.restrictions",
                "entertainment.types",
                "entertainment.venues",
                "shopping.brands",
                "shopping.stores",
            ],
            "routines": [
                "daily.morning",
                "daily.work_start",
                "daily.lunch",
                "daily.work_end",
                "daily.evening",
                "weekly.planning",
                "weekly.review",
                "weekly.social",
                "monthly.bills",
                "monthly.review",
                "seasonal.activities",
                "travel.preparation",
                "travel.follow_up",
            ],
            "health": [
                "medical.conditions",
                "medical.medications",
                "medical.allergies",
                "medical.appointments",
                "fitness.activities",
                "fitness.goals",
                "fitness.tracking",
                "mental_health.practices",
                "mental_health.support",
                "nutrition.diet",
                "nutrition.restrictions",
                "sleep.schedule",
                "sleep.quality",
            ],
            "finance": [
                "accounts.banking",
                "accounts.credit",
                "accounts.investment",
                "accounts.retirement",
                "budget.income",
                "budget.expenses",
                "budget.categories",
                "bills.recurring",
                "bills.due_dates",
                "investments.portfolio",
                "investments.goals",
                "taxes.documents",
                "taxes.deadlines",
            ],
            "projects": [
                "work.current",
                "work.completed",
                "work.planned",
                "personal.current",
                "personal.completed",
                "personal.planned",
                "home.maintenance",
                "home.improvement",
                "learning.courses",
                "learning.skills",
                "creative.writing",
                "creative.art",
                "creative.music",
            ],
            "learning": [
                "courses.online",
                "courses.formal",
                "books.reading",
                "books.to_read",
                "skills.technical",
                "skills.soft",
                "languages.studying",
                "languages.target",
                "certifications.pursuing",
                "certifications.maintaining",
                "conferences.attended",
                "conferences.planned",
            ],
        },
    }

    @classmethod
    def get_preset(cls, version: TaxonomyVersion) -> dict[str, list[str]]:
        """
        Get a taxonomy preset for a specific version.

        Args:
            version: The taxonomy version to retrieve

        Returns:
            Dictionary with first-level categories and their subcategories (empty for dynamic expansion)
        """
        return cls.PRESETS.get(version, cls.PRESETS[TaxonomyVersion.GENERAL]).copy()

    @classmethod
    def get_first_level_categories(cls, version: TaxonomyVersion) -> list[str]:
        """
        Get only the first-level categories for a taxonomy version.

        Args:
            version: The taxonomy version

        Returns:
            List of first-level category names
        """
        preset = cls.get_preset(version)
        return list(preset.keys())

    @classmethod
    def list_versions(cls) -> list[TaxonomyVersion]:
        """
        List all available taxonomy versions.

        Returns:
            List of available TaxonomyVersion enums
        """
        return list(TaxonomyVersion)
